name: flutter_tubes
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.1.1  
  url_launcher: ^6.0.10
  webview_flutter: ^4.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6
  http: ^1.0.0
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpeg
    - assets/logo2.jpg
    - assets/layanan1.jpg
    - assets/layanan2.jpeg
    - assets/layanan3.jpeg
    - assets/fasilitas1.jpeg
    - assets/fasilitas2.jpeg
    - assets/fasilitas3.jpg
    - assets/harsya.jpeg
    - assets/Aditya.jpeg
    - assets/bella.jpeg
    - assets/charles.jpeg
    - assets/diana.jpeg
    - assets/rahmat.jpeg
    - assets/riyan.jpeg
    - assets/yulia.jpeg
    - assets/vip_room.jpg
    - assets/standar_room.jpg
    - assets/suite_room.jpg
