// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCROHHZhoj8m-GoIfqVqstc9NHErAroJ20',
    appId: '1:45050059231:web:9cc481c0dba6f88f9c4c6a',
    messagingSenderId: '45050059231',
    projectId: 'healtycarefirebase',
    authDomain: 'healtycarefirebase.firebaseapp.com',
    databaseURL: 'https://healtycarefirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healtycarefirebase.firebasestorage.app',
    measurementId: 'G-FWMRXEL53R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzY0XoyK4KDJr6v7wYXrGAnUXki_5ssSc',
    appId: '1:45050059231:android:8c3e6d370d07df779c4c6a',
    messagingSenderId: '45050059231',
    projectId: 'healtycarefirebase',
    databaseURL: 'https://healtycarefirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healtycarefirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4a2bYVgFr48MCk6ZpxijW3GnUU8crIVk',
    appId: '1:45050059231:ios:04b9e1cce29e58b59c4c6a',
    messagingSenderId: '45050059231',
    projectId: 'healtycarefirebase',
    databaseURL: 'https://healtycarefirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healtycarefirebase.firebasestorage.app',
    iosBundleId: 'com.syong.flutterTubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4a2bYVgFr48MCk6ZpxijW3GnUU8crIVk',
    appId: '1:45050059231:ios:6582130129d612829c4c6a',
    messagingSenderId: '45050059231',
    projectId: 'healtycarefirebase',
    databaseURL: 'https://healtycarefirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healtycarefirebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterTubes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCROHHZhoj8m-GoIfqVqstc9NHErAroJ20',
    appId: '1:45050059231:web:bad48bfa5d6b8b179c4c6a',
    messagingSenderId: '45050059231',
    projectId: 'healtycarefirebase',
    authDomain: 'healtycarefirebase.firebaseapp.com',
    databaseURL: 'https://healtycarefirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healtycarefirebase.firebasestorage.app',
    measurementId: 'G-T4H61TVCV6',
  );
}
